[unstable]
build-std = ["core", "alloc", "compiler_builtins"]

[target.riscv64imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tbootloader/link.ld",
  "-C", "target-cpu=generic",
  "-C", "linker-plugin-lto",
]
